---
Name: gridfieldajaxrefresh
Before: 'app/*'
After: 'framework/*','cms/*'
---

SilverStripe\Forms\GridField\GridFieldConfig_Base:
  extensions:
    - GridFieldAjaxRefresh\GridFieldAjaxRefresh_Base

SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor:
  extensions:
    - GridFieldAjaxRefresh\GridFieldAjaxRefresh_RecordEditor
